// react-app/src/App.js
import React from 'react';
import { BrowserRouter } from "react-router-dom";
import Router from "./Router";
import './App.css';

import Nav from "./components/Nav";

function App() {
  return (
    <BrowserRouter>
    <div className="container">
      <Nav />
        <Router />
    </div>
    </BrowserRouter>
  );
}

export default App;

// client/src/App.vue
<template>
  <div class="container">
    <Header></Header>
    <Nav></Nav>

    <router-view/>

    <MyFooter></MyFooter>
  </div>
</template>

<style lang="scss">
</style>

<script>
import Nav from './components/Nav';
import MyFooter from './components/Footer';
import Header from './components/Header';
export default {
    components: {
      Nav, MyFooter, Header
    }
}
</script>
