// react-app/src/views/Home.js
<template>
  <div className="home">
    
    <section className="hero is-large is-light is-bold">
    <div className="hero-body">
      <div className="container">
        <h1 className="title">
          Primary bold title
        </h1>
        <h2 className="subtitle">
          Primary bold subtitle
        </h2>
      </div>
    </div>
  </section>
  </div>
</template>

<script>
// @ is an alias to /src


export default {
  name: 'home',
  components: {
    
  },
};
</script>

// client/src/views/Home.vue
<template>
  <div class="home">
    
    <section class="hero is-primary is-medium">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Medium title
      </h1>
      <h2 class="subtitle">
        Medium subtitle
      </h2>
    </div>
  </div>
</section>
  </div>
</template>
